// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	user2 "test/internal/application/service/user"
	"test/internal/infrastructure/api"
	user3 "test/internal/infrastructure/api/user"
	"test/internal/infrastructure/persistance"
	"test/internal/infrastructure/persistance/user"
)

// Injectors from wire.go:

func InitializeAPI(config persistance.Config) (*api.Router, error) {
	db, err := persistance.NewConnection(config)
	if err != nil {
		return nil, err
	}
	userRepository := user.NewUserRepository(db)
	userService := user2.NewUserService(userRepository)
	handler := user3.NewHandler(userService)
	router := api.NewRouter(handler)
	return router, nil
}
